"""add_phone_number_coloum

Revision ID: 7116dc62808a
Revises: ad2a334c6079
Create Date: 2024-03-19 18:44:10.996233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7116dc62808a'
down_revision: Union[str, None] = 'ad2a334c6079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_phone_no', sa.String(),nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', sa.Column('user_phone_no', sa.String()))
    # ### end Alembic commands ###
