"""some changes

Revision ID: 979d9b78ef27
Revises: 57a6e3e851c9
Create Date: 2024-04-02 20:44:33.292622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979d9b78ef27'
down_revision: Union[str, None] = '57a6e3e851c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoes', sa.Column('shoes_stock', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('shoes', sa.Column('shoes_description', sa.Text(), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'shoes_description')
    op.drop_column('shoes', 'shoes_stock')
    # ### end Alembic commands ###
