"""new orders

Revision ID: c0e39f5ad092
Revises: 7116dc62808a
Create Date: 2024-03-21 22:50:12.974854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e39f5ad092'
down_revision: Union[str, None] = '7116dc62808a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('owner_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('user_address', sa.String(), server_default=sa.text("'None'"), nullable=False))
    op.add_column('orders', sa.Column('product_image', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('shoes_category', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('size', sa.Integer(), server_default=sa.text('9'), nullable=False))
    op.add_column('orders', sa.Column('product_quantity', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('orders', sa.Column('shipping_method', sa.String(), server_default=sa.text("'processing'"), nullable=False))
    
    op.alter_column('users', 'user_address',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_address',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'product_quantity')
    op.drop_column('orders', 'size')
    op.drop_column('orders', 'shoes_category')
    op.drop_column('orders', 'product_image')
    op.drop_column('orders', 'user_address')
    op.drop_column('orders', 'owner_name')
    # ### end Alembic commands ###
