"""change cart

Revision ID: ebbe306bcab2
Revises: c0e39f5ad092
Create Date: 2024-03-21 23:23:02.368389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbe306bcab2'
down_revision: Union[str, None] = 'c0e39f5ad092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('cart_owner_email_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_owner_email_fkey', 'cart', 'users', ['owner_email'], ['email'], ondelete='CASCADE')
    op.drop_column('cart', 'owner_id')
    # ### end Alembic commands ###
